# Generated by Django 4.2.1 on 2023-06-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
